platform :ios, '13.2'

target 'Carangas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carangas
  pod 'Alamofire'

end
